# Создаем папку в которой хранится docker-compose
- name: Ensure app folder
  file:
    path: '{{ app_root }}'
    state: directory
    owner: '{{ app_owner }}'

- name: Rsync pipelines and solids
  synchronize:
    src: "{{ lookup('pipe', 'pwd') }}/cube"
    dest: '{{ app_root }}'
    recursive: yes
    delete: true
    rsync_opts:
    - '--exclude=.*'
    - '--exclude=*/__pycache__'

- name: Setup docker-compose.yml
  when: deploy == "yes"
  template:
    src: docker-compose.yml
    dest: '{{ app_root }}'
  notify: Reload docker-compose
