version: '3'

services:
  cube_master:
    image: ${DOCKER_REGISTRY:-local}:master-${VERSION_TAG:-latest}
    build:
      context: build
      dockerfile: master.Dockerfile
      args:
        origin: ${ORIGIN:-dagster-io}
        branch: ${BRANCH:-master}

  cube_runner:
    image: ${DOCKER_REGISTRY:-local}:runner-${VERSION_TAG:-latest}
    build:
      context: build
      dockerfile: runner.Dockerfile
      args:
        origin: ${ORIGIN:-dagster-io}
        branch: ${BRANCH:-master}

  cube_worker:
    image: ${DOCKER_REGISTRY:-local}:worker-${VERSION_TAG:-latest}
    build:
      context: .
      dockerfile: worker.Dockerfile
      args:
        origin: ${ORIGIN:-dagster-io}
        branch: ${BRANCH:-master}
